# group_vars/all.yml
---
# ================== VARIÁVEIS GLOBAIS ==================

# Usuário remoto padrão (se não houver override)
ansible_user: ansible

# Diretórios comuns (cada SO pode sobrescrever)
log_dir: "/var/log/ansible"
temp_dir: "/tmp/ansible"

# Controle de reinício
allow_reboot: false
reboot_timeout: 1200

# Timezone padrão
timezone: "UTC"

# NTP global
ntp_servers:
  - a.st1.ntp.br
  - b.st1.ntp.br
  - c.st1.ntp.br
  - d.st1.ntp.br

ntp_servers_pool:
  - pool.ntp.br

# Pacotes que *todos* os hosts devem instalar
packages_common: []

# Banners
banner:
  pre_login: |
    ***************************************************************************
    *                                                                         *
    *         █████╗ ███████╗███████╗████████╗██╗  ██╗ █████╗ ██████╗         *
    *        ██╔══██╗██╔════╝██╔════╝╚══██╔══╝██║  ██║██╔══██╗██╔══██╗        *
    *        ███████║█████╗  ███████╗   ██║   ███████║███████║██████╔╝        *
    *        ██╔══██║██╔══╝  ╚════██║   ██║   ██╔══██║██╔══██║██╔══██╗        *
    *        ██║  ██║███████╗███████║   ██║   ██║  ██║██║  ██║██║  ██║        *
    *        ╚═╝  ╚═╝╚══════╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝        *
    *                                                                         *
    *                        SISTEMA DE ACESSO RESTRITO                       *
    *                                                                         *
    *        Este sistema é propriedade exclusiva da [AESTHAR].               *
    *        O acesso está restrito a usuários autorizados.                   *
    *        Todas as atividades são monitoradas e registradas.               *
    *        Uso não autorizado resultará em ações legais.                    *
    *                                                                         *
    ***************************************************************************

  remote_login: "{{ banner.pre_login }}"

  post_login: |
    #!/bin/bash
    echo
    echo "*********************************************************************"
    echo "*                 [ AESTHAR ] - SISTEMA AUTORIZADO                  *"
    echo "*   Último acesso registrado em: $(date -R)         *"
    echo "*********************************************************************"
    echo
    echo "► Hostname:       $(hostname)"
    echo "► Kernel:         $(uname -r) $(uname -m)"
    echo "► Usuário:        $(whoami)"
    echo "► IP:             $(hostname -I | awk '{print $1}')"
    echo "► Sessões ativas: $(who | wc -l)"
    echo
    echo "*********************************************************************"
    echo "*  [!] Este sistema é monitorado. Consulte as políticas de uso em:  *"
    echo "*         https://www.aesthar.com.br/politicas-de-seguranca         *"
    echo "*********************************************************************"
    echo
