# group_vars/network.yml
---
# === VyOS BGP/NAT ===
vyos:
  nat:
    outbound_interface: eth0
    rules:
      - id: 10
        translation: masquerade
  bgp:
    local_as: 64512
    neighbors:
      # IPv4
      - {address: 172.16.200.11, remote_as: 64513, afi: ipv4-unicast}
      - {address: 172.16.200.21, remote_as: 64513, afi: ipv4-unicast}
      - {address: 172.16.200.22, remote_as: 64513, afi: ipv4-unicast}
      # IPv6
      - {address: fd00:172:16:200::11, remote_as: 64513, afi: ipv6-unicast}
      - {address: fd00:172:16:200::21, remote_as: 64513, afi: ipv6-unicast}
      - {address: fd00:172:16:200::22, remote_as: 64513, afi: ipv6-unicast}
    settings:
      maximum_paths_ebgp: 4
      multipath_relax: true
  ndp_proxy:
    interface: eth0
    prefix: 2804:14d:3280:4043::eeee:0/112
