# k8s-ansible/inventory/production.yaml
---
all:
  children:
    vyos:
      children:
        network:
          hosts:
            k8s-vyos:
              ansible_host: 172.16.1.254

    linux:
      children:
        kubeadm:
          children:
            k8s_cluster:
              children:
                k8s_masters:
                  hosts:
                    k8s-master01:
                      ansible_host: 172.16.1.11
                k8s_workers:
                  hosts:
                    k8s-worker01:
                      ansible_host: 172.16.1.21
                    k8s-worker02:
                      ansible_host: 172.16.1.22
