# group_vars/linux.yml
# ================== CONFIGURAÇÃO LINUX ==================

# Usuário remoto padrão
ansible_user: ansible

ansible_connection: ssh
ansible_ssh_port: 22
# ansible_shell_type: bash
# ansible_shell_executable: /bin/bash
# ansible_python_interpreter: /usr/bin/python3.9
# ansible_remote_tmp: /tmp/ansible/.ansible/tmp

# Escalonamento
ansible_become: true
ansible_become_method: sudo

# Configurações regionais
timezone: "America/Sao_Paulo"
locale: "en_US.UTF-8"

# Diretórios específicos
log_dir: "/var/log"
temp_dir: "/tmp"

# Pacotes Linux
packages_common:
  - curl
  - vim
  - unzip
  - htop
  - btop
  - tmux
  - bash-completion
  - qemu-guest-agent
